name: Build Sample Mobile App for iOS and Android

on:
  workflow_dispatch:

jobs:
#  build_ios:
#    name: Build the iOS version of the app
#    runs-on: macos-12

  build_android:
    name: Build the Android version of the app

    #ubuntu-20 (latest right now) https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-latest

    steps:    
      #checkout project
      - uses: actions/checkout@v3

      #setup java? has java 8/11/17
      - name: JDK11
        uses: actions/setup-java@v3
        with:
          cache: gradle
          java-version: '11'
          distribution: 'zulu'

      #setup node version 14, may work with newer but for now aim for 14.
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      #setup yarn+other tools.
      - name: Setup Yarn and tools
        run: |
          npm -g i yarn

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      #setup env
      - name: Setup Env
        run: |
          yarn install

      #run gradle 
      - name: Actual Gradle Build
        run: |
          cd android
          ./gradlew bundleRelease
